### ISSUE TITLE
Article Template Master List

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/scratchpad#3]
This issue tracks all the issues for each template. Once this is completed, the project is officially done!

- [ ] General Issues #6 
- [ ] Generic Article Template #13
- [ ] Building-Landmark Article Template #14
- [ ] Character Article Template #15
- [ ] Condition Article Template #16
- [ ] Military Conflict Article Template #12 
- [ ] Document Article Template #17
- [ ] Ethnicity Template #18
- [ ] Geography Template #19
- [ ] Item Template #20
- [ ] Language Template #21
- [ ] Material Template #22
- [ ] Military Unit Template #4 
- [ ] Myths & Legends Template #23
- [ ] Natural Law Template #24
- [ ] Organization Template #11 
- [ ] Plot Template #25
- [ ] Profession Template #26
- [ ] Prose Template #27
- [ ] Session Report Template #28
- [ ] Settlement Template #29
- [ ] Species Template #30
- [ ] Spell Template #31
- [ ] Technology Template #32
- [ ] Title & Rank Template #33
- [ ] Tradition & Ritual Template #34
- [ ] Vehicle Template #35
